---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: matrix-results-pv
spec:
  capacity:
    storage: 1Gi  # Size of the storage
  accessModes:
    - ReadWriteOnce  # Only one node can write at a time, but many can read
  hostPath:
    path: "/mnt/data"  # This is where the data will be stored on the host node
